import React from "react";
import {
  BrazilFlag,
  FranceFlag,
  ArgentinaFlag,
  GermanyFlag,
  PortugalFlag,
  SpainFlag,
  CanadaFlag,
  BosniaHerzegovinaFlag,
  MoroccoFlag,
  SenegalFlag,
  AlgeriaFlag,
  HaitiFlag,
  ScotlandFlag,
  AustraliaFlag,
  TurkeyFlag,
  MexicoFlag,
  SouthAfricaFlag,
  SouthKoreaFlag,
  CzechiaFlag,
  UnitedStatesFlag,
  ParaguayFlag,
  CuracaoFlag,
  NetherlandsFlag,
  JapanFlag,
  IvoryCoastFlag,
  EcuadorFlag,
  SwedenFlag,
  TunisiaFlag,
  EnglandFlag,
  ItalyFlag,
  BelgiumFlag,
  CroatiaFlag,
  PolandFlag,
  UruguayFlag,
  ColombiaFlag,
  VenezuelaFlag,
  PanamaFlag,
  CostaRicaFlag,
  JamaicaFlag,
  NewZealandFlag,
  EgyptFlag,
  GhanaFlag,
  NigeriaFlag,
  CameroonFlag,
  CapeVerdeFlag,
  SaudiArabiaFlag,
  IranFlag,
  QatarFlag,
  UzbekistanFlag,
} from "./flags";

interface FlagIconProps {
  flag: string;
  className?: string;
}

const FLAGS: Record<string, React.FC<{ className?: string }>> = {
  brazil: BrazilFlag,
  france: FranceFlag,
  argentina: ArgentinaFlag,
  germany: GermanyFlag,
  portugal: PortugalFlag,
  spain: SpainFlag,
  canada: CanadaFlag,
  bosnia: BosniaHerzegovinaFlag,
  morocco: MoroccoFlag,
  senegal: SenegalFlag,
  algeria: AlgeriaFlag,
  haiti: HaitiFlag,
  scotland: ScotlandFlag,
  australia: AustraliaFlag,
  turkey: TurkeyFlag,
  mexico: MexicoFlag,
  southafrica: SouthAfricaFlag,
  southkorea: SouthKoreaFlag,
  czechia: CzechiaFlag,
  usa: UnitedStatesFlag,
  paraguay: ParaguayFlag,
  curacao: CuracaoFlag,
  netherlands: NetherlandsFlag,
  japan: JapanFlag,
  ivorycoast: IvoryCoastFlag,
  ecuador: EcuadorFlag,
  sweden: SwedenFlag,
  tunisia: TunisiaFlag,
  england: EnglandFlag,
  italy: ItalyFlag,
  belgium: BelgiumFlag,
  croatia: CroatiaFlag,
  poland: PolandFlag,
  uruguay: UruguayFlag,
  colombia: ColombiaFlag,
  venezuela: VenezuelaFlag,
  panama: PanamaFlag,
  costarica: CostaRicaFlag,
  jamaica: JamaicaFlag,
  newzealand: NewZealandFlag,
  egypt: EgyptFlag,
  ghana: GhanaFlag,
  nigeria: NigeriaFlag,
  cameroon: CameroonFlag,
  capeverde: CapeVerdeFlag,
  saudiarabia: SaudiArabiaFlag,
  iran: IranFlag,
  qatar: QatarFlag,
  uzbekistan: UzbekistanFlag,
};

export const FlagIcon: React.FC<FlagIconProps> = ({ flag, className = "w-16 h-12" }) => {
  const Flag = FLAGS[flag.toLowerCase()];
  if (Flag) {
    return <Flag className={className} />;
  }
  return (
    <div className={`flex items-center justify-center bg-gray-500 rounded text-white text-xs ${className}`}>
      {flag}
    </div>
  );
};
