#!/usr/bin/env bash
#
# traffic-report-scheduled.sh — fast-forward the checkout, then run the report.
#
# Wrapper for unattended/scheduled use (the systemd timer installed by
# shell_scripts/08_setup_monitoring.sh, or a manual "one command" run). It exists
# to guarantee the report is generated by the CURRENT committed traffic-report.sh
# rather than a stale prod checkout — the failure mode we hit when the box ran an
# old script and produced a 2-section summary missing the status/geo/suspect/delta
# sections.
#
# Steps:
#   1. git pull --ff-only   — fail-soft: a pull failure (offline, diverged, auth)
#      still yields a report from the on-disk checkout, so monitoring never goes
#      dark just because origin is unreachable.
#   2. exec scripts/traffic-report.sh "$@"   — all args pass through (log path,
#      out dir), so the wrapper is a drop-in replacement for a direct call.
#
# Idempotent and side-effect-light: it only fast-forwards and writes a report; it
# never commits, pushes, or force-updates. Committing/sharing reports stays a
# human step (the report dir is tracked, so new summaries show up as untracked
# files for the human to commit if they want to share them).

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO="$(cd "$SCRIPT_DIR/.." && pwd)"
cd "$REPO"

echo "==> [scheduled] git -C $REPO pull --ff-only"
if git pull --ff-only; then
  echo "==> Checkout up to date."
else
  echo "!!  git pull --ff-only failed — generating the report from the current" \
       "on-disk checkout instead." >&2
fi

echo "==> Running traffic report..."
exec bash "$REPO/scripts/traffic-report.sh" "$@"
